'use client';

import { useEffect, useState } from 'react';
import { getAnalyticsOverview, getCampaignAnalytics, syncCampaignReplies, type AnalyticsOverview, type CampaignAnalytics } from '../analytics.api';

const metricLabels: Array<[keyof AnalyticsOverview['metrics'], string]> = [['sent', 'Sent'], ['scheduled', 'Scheduled'], ['failed', 'Failed'], ['suppressed', 'Suppressed'], ['replies', 'Replies'], ['unsubscribes', 'Unsubscribes']];
export function AnalyticsDashboard() {
  const [overview, setOverview] = useState<AnalyticsOverview | null>(null); const [detail, setDetail] = useState<CampaignAnalytics | null>(null); const [selected, setSelected] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = () => getAnalyticsOverview().then((data) => { setOverview(data); setSelected((current) => current || data.campaigns[0]?.id || ''); }).catch((error: Error) => setMessage(error.message)); useEffect(() => { refresh(); }, []); useEffect(() => { if (selected) getCampaignAnalytics(selected).then(setDetail).catch((error: Error) => setMessage(error.message)); }, [selected]);
  async function syncReplies() { if (!selected) return; setBusy(true); try { const result = await syncCampaignReplies(selected); setMessage(`${result.matched} new reply${result.matched === 1 ? '' : 'ies'} matched from ${result.scanned} recent message headers.`); setDetail(await getCampaignAnalytics(selected)); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not sync replies.'); } finally { setBusy(false); } }
  return <section className="analytics-dashboard"><div className="section-heading"><div><span className="eyebrow">PHASE 7 · ANALYTICS</span><h2>Campaign performance</h2><p>Monitor campaign activity and recipient outcomes. Reply sync matches Gmail metadata only, never message bodies.</p></div></div>{overview && <div className="metric-grid">{metricLabels.map(([key, label]) => <div key={key}><strong>{overview.metrics[key]}</strong><span>{label}</span></div>)}</div>}<div className="analytics-detail"><div className="analytics-toolbar"><label>Campaign<select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="">Choose campaign</option>{overview?.campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.name} · {campaign.status}</option>)}</select></label><button className="button secondary" disabled={busy || !selected} onClick={syncReplies}>{busy ? 'Syncing…' : 'Sync reply metadata'}</button></div>{message && <div className="message">{message}</div>}{detail && <><div className="activity-list"><h3>Recent activity</h3>{detail.activity.length ? detail.activity.slice(0, 12).map((event) => <div key={event.id}><span>{new Date(event.at).toLocaleString()}</span><strong>{event.type}</strong><small>{event.recipient}{event.detail ? ` · ${event.detail}` : ''}</small></div>) : <p>No campaign activity yet.</p>}</div><div className="recipient-list"><h3>Recipient status</h3>{detail.recipients.slice(0, 20).map((recipient) => <div key={recipient.id}><div><strong>{recipient.name || recipient.email}</strong><span>{recipient.email}{recipient.company ? ` · ${recipient.company}` : ''}</span></div><small className={`recipient-status ${recipient.status}`}>{recipient.repliedAt ? 'replied' : recipient.status}</small></div>)}</div></>}</div>{overview?.senders.length ? <div className="sender-performance"><h3>Sender activity</h3>{overview.senders.map((sender) => <div key={sender.senderId}><strong>{sender.email}</strong><span>{sender.sent} sent · {sender.failed} failed · {sender.replies} replies</span></div>)}</div> : null}</section>;
}
