'use client';

import { ChangeEvent, useEffect, useState } from 'react';
import { getContactLists, importFile, previewFile } from '../contacts.api';
import type { ContactField, ContactList, ImportPreview } from '../types';

const fields: Array<{ id: ContactField; label: string; required?: boolean }> = [{ id: 'email', label: 'Email', required: true }, { id: 'firstName', label: 'First name' }, { id: 'lastName', label: 'Last name' }, { id: 'company', label: 'Company' }, { id: 'jobTitle', label: 'Job title' }, { id: 'website', label: 'Website' }];
export function ContactImporter() {
  const [file, setFile] = useState<File | null>(null); const [listName, setListName] = useState(''); const [preview, setPreview] = useState<ImportPreview | null>(null); const [mapping, setMapping] = useState<Partial<Record<ContactField, string>>>({}); const [lists, setLists] = useState<ContactList[]>([]); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const refresh = () => getContactLists().then(setLists).catch(() => undefined); useEffect(() => { refresh(); }, []);
  async function chooseFile(event: ChangeEvent<HTMLInputElement>) { const selected = event.target.files?.[0]; if (!selected) return; setFile(selected); setPreview(null); setMessage(''); setBusy(true); try { const result = await previewFile(selected); setPreview(result); setMapping(result.suggestedMapping); if (!listName) setListName(selected.name.replace(/\.[^.]+$/, '')); } catch (error) { setMessage(error instanceof Error ? error.message : 'Preview failed.'); } finally { setBusy(false); } }
  async function updateMapping(field: ContactField, value: string) { const next = { ...mapping, [field]: value }; setMapping(next); if (!file) return; setBusy(true); try { setPreview(await previewFile(file, next as Record<string, string>)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not update preview.'); } finally { setBusy(false); } }
  async function commit() { if (!file || !preview) return; setBusy(true); setMessage(''); try { const result = await importFile(file, listName || file.name, mapping as Record<string, string>); setMessage(`${result.list.totalContacts} contacts imported into “${result.list.name}”.`); setFile(null); setPreview(null); refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : 'Import failed.'); } finally { setBusy(false); } }
  return <section className="contact-importer"><div className="section-heading"><div><span className="eyebrow">PHASE 3 · CONTACTS</span><h2>Import prospects</h2><p>Upload CSV, XLS, or XLSX files. Invalid and duplicate email records are skipped before any contacts are saved.</p></div></div><label className="file-picker"> <input type="file" accept=".csv,.xls,.xlsx" onChange={chooseFile} /> <span>{file ? file.name : 'Choose CSV, XLS, or XLSX'}</span><small>Maximum 10 MB · 20,000 contacts</small></label>{busy && <p className="loading">Processing your file…</p>}{message && <div className="message">{message}</div>}{preview && <div className="import-review"><div className="list-name"><label>List name<input value={listName} onChange={(event) => setListName(event.target.value)} /></label></div><h3>Map columns</h3><div className="mapping-grid">{fields.map((field) => <label key={field.id}>{field.label}{field.required && ' *'}<select value={mapping[field.id] ?? ''} onChange={(event) => updateMapping(field.id, event.target.value)}><option value="">Not mapped</option>{preview.headers.map((header) => <option key={header} value={header}>{header}</option>)}</select></label>)}</div><div className="import-stats"><span><strong>{preview.summary.rowsRead}</strong> rows read</span><span><strong>{preview.summary.valid}</strong> valid</span><span><strong>{preview.summary.invalid}</strong> invalid</span><span><strong>{preview.summary.duplicate}</strong> duplicates</span><span><strong>{preview.summary.existing}</strong> already imported</span><span><strong>{preview.summary.incomplete}</strong> missing first name</span></div>{preview.preview.length > 0 && <div className="contact-preview"><h3>Preview</h3><div className="table"><div className="table-row table-head"><span>Email</span><span>Name</span><span>Company</span><span>Status</span></div>{preview.preview.map((contact) => <div className="table-row" key={contact.email}><span>{contact.email}</span><span>{[contact.firstName, contact.lastName].filter(Boolean).join(' ') || '—'}</span><span>{contact.company || '—'}</span><span>{contact.status}</span></div>)}</div></div>}<button className="button" disabled={busy || !mapping.email || !listName.trim()} onClick={commit}>Import {preview.summary.readyToImport} validated contacts</button></div>}<div className="lists"><h3>Your lists</h3>{lists.length ? lists.map((list) => <div className="list-row" key={list.id}><strong>{list.name}</strong><span>{list.totalContacts} contacts</span></div>) : <p>No contact lists yet.</p>}</div></section>;
}
