import { env } from '../../config/env.js';
import { generatedTemplatesSchema } from './template.schemas.js';

type Context = { audience: string; objective: string; value: string; tone: string; additionalContext: string };
const templateJsonSchema = { type: 'object', properties: { templates: { type: 'array', minItems: 5, maxItems: 5, items: { type: 'object', properties: { approach: { type: 'string' }, subject: { type: 'string' }, body: { type: 'string' }, variables: { type: 'array', items: { type: 'string' } } }, required: ['approach', 'subject', 'body', 'variables'] } } }, required: ['templates'] };
export async function generateTemplates(context: Context) {
  if (!env.GEMINI_API_KEY) { const error = new Error('Gemini is not configured. Add GEMINI_API_KEY to the server environment.'); (error as Error & { status: number }).status = 503; throw error; }
  const prompt = `You write compliant, concise B2B outreach templates. Create exactly five distinct email templates from ONLY these campaign facts. Do not invent facts about prospects, their companies, results, customers, funding, news, or personal observations. Avoid misleading urgency, spammy language, unverifiable claims, and guarantees. Use personalization variables only when helpful: {{first_name}}, {{last_name}}, {{company}}, {{job_title}}, {{website}}, or clearly named custom variables. Return JSON only.\n\nCampaign facts:\nAudience: ${context.audience}\nObjective: ${context.objective}\nValue proposition: ${context.value}\nTone: ${context.tone}\nAdditional context: ${context.additionalContext || 'None provided'}\n\nUse five different approaches: concise introduction, problem/value, relevant business angle, question-led, and short professional outreach. JSON shape: {"templates":[{"approach":"...","subject":"...","body":"...","variables":["first_name"]}]}`;
  const response = await fetch('https://generativelanguage.googleapis.com/v1beta/interactions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-goog-api-key': env.GEMINI_API_KEY }, body: JSON.stringify({ model: 'gemini-3.6-flash', input: prompt, store: false, response_format: { type: 'text', mime_type: 'application/json', schema: templateJsonSchema } }) });
  const payload = await response.json() as { output_text?: string; steps?: Array<{ type?: string; content?: Array<{ type?: string; text?: string }> }>; error?: { message?: string } };
  if (!response.ok) { const error = new Error(payload.error?.message ?? 'Gemini could not generate templates.'); (error as Error & { status: number }).status = response.status; throw error; }
  const text = payload.output_text ?? payload.steps?.filter((step) => step.type === 'model_output').flatMap((step) => step.content ?? []).filter((content) => content.type === 'text').map((content) => content.text ?? '').join('') ?? '';
  try { return generatedTemplatesSchema.parse(JSON.parse(text)); } catch { throw new Error('Gemini returned an invalid template response. Please try again.'); }
}
